apiVersion: v1
kind: Service
metadata:
  name: yhstore
  labels:
    app: yhstore
spec:
  type: NodePort
  selector:
    app: yhstore
  ports:
  - name: http
    port: 8083
    targetPort: 8083

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yhstore
spec:
  # 节点数，设置为多个可以实现负载均衡效果
  replicas: 1
  selector:
    matchLabels:
      app: yhstore
  template:
    metadata:
      labels:
        app: yhstore
    spec:
      hostAliases:
      - ip: "192.168.0.200"
        hostnames:
        - "gz.yaohuiw.net"
      - ip: "192.168.0.200"
        hostnames:
        - "login.yaohuiw.net"
      - ip: "192.168.0.200"
        hostnames:
        - "pay.yaohuiw.net"
      - ip: "192.168.0.200"
        hostnames:
        - "boss.yaohuiw.net"
      containers:
      - name: yhstore
       #镜像名
        image: registry.cn-shenzhen.aliyuncs.com/jwh/yhstore
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: JAVA_OPTS
          value: -Xms1024m -Xmx1024m -Xmn384m -Xss228k -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/log
        - name: PARAMS
          value: --spring.profiles.active=dev --eureka.client.serviceUrl.defaultZone=http://eureka-0:8000/eureka/,http://eureka-1:8000/eureka/
        volumeMounts:
        - mountPath: /opt/logs
          name: yhstore-log
      restartPolicy: Always
      volumes:
      - name: yhstore-log
        nfs:
          server: 192.168.0.200
          path: /data1/k8s-vloume/yhstore-log

