apiVersion: v1
kind: Service
metadata:
  name: yhstore-cache
  labels:
    app: yhstore-cache
spec:
  type: NodePort
  selector:
    app: yhstore-cache
  ports:
  - name: http
    port: 9150
    targetPort: 9150
    #nodePort: 32000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yhstore-cache
spec:
  # 节点数，设置为多个可以实现负载均衡效果
  replicas: 2
  selector:
    matchLabels:
      app: yhstore-cache
  template:
    metadata:
      labels:
        app: yhstore-cache
    spec:
      hostAliases:
      - ip: "192.168.0.200"
        hostnames:
        - "gz.yaohuiw.net"
      - ip: "192.168.0.200"
        hostnames:
        - "login.yaohuiw.net"
      - ip: "192.168.0.200"
        hostnames:
        - "pay.yaohuiw.net"
      - ip: "192.168.0.200"
        hostnames:
        - "boss.yaohuiw.net"
      containers:
      - name: yhstore-cache
       #镜像名
        image: registry.cn-shenzhen.aliyuncs.com/jwh/yhstore-cache
        imagePullPolicy: Always
        ports:
        - containerPort: 9150
        env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx128m -Xmn48m -Xss228k -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/log
        - name: PARAMS
          value: --spring.profiles.active=dev --eureka.client.serviceUrl.defaultZone=http://eureka-0:8000/eureka/,http://eureka-1:8000/eureka/
        volumeMounts:
        - mountPath: /opt/logs
          name: yhstore-cache-log
      imagePullSecrets:
      - name: aliyuncs
      restartPolicy: Always
      volumes:
      - name: yhstore-cache-log
        nfs:
          server: 192.168.0.200
          path: /home/kvm/k8s-vloume/yhstore-cache-log

